# fly.toml app configuration file generated for djit on 2025-06-24T00:03:10+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'djit'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

    

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


