spring:
  application:
    name: djit
  datasource:
    url: jdbc:mysql://localhost:3307/djit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8090