spring:
  application:
    name: djit
  datasource:
    url: jdbc:mysql://152.67.207.90:3306/djit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 10
  thymeleaf:
    cache: true
server:
  port: 8090
file:
  upload:
    path: ${UPLOAD_PATH:/home/ubuntu/djit/uploads/}
app:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  google:
    maps:
      api-key: ${GOOGLE_MAPS_API_KEY}
